version: '3.1'

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - my_network
    container_name: app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: PyTryDB
    ports:
      - "5432:5432"
    networks:
      - my_network
networks:
  my_network: