version: '3.1'

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./static:/app/static
      - ./tests:/app/tests
    networks:
      - my_network
    container_name: app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: PyTryDB
    volumes:
      - ./pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "maydurov2004@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "123456"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - my_network
networks:
  my_network:
